CREATE TABLE public.USER (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(1000),
    EMAIL VARCHAR(1000)
);


CREATE TABLE public.CATEGORY (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(1000)
);


CREATE TABLE public.TRANSACTION (
    ID SERIAL PRIMARY KEY,
    T_TYPE VARCHAR(1000),
    INITIAL_DATE DATE,
    END_DATE DATE,
    CATEGORY_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL
);


CREATE TABLE public.TRANSACTION_DETAIL (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(1000),
    DESCRIPTION VARCHAR(1000),
    T_MONTH INTEGER,
    T_YEAR INTEGER,
    INSTALLMENT INTEGER,
    PAYMENT_METHOD VARCHAR(1000),
    PAID BOOLEAN,
    TRANSACTION_ID INTEGER NOT NULL
);


ALTER TABLE public.TRANSACTION
ADD CONSTRAINT CATEGORY_TRANSACTION_FK FOREIGN KEY (CATEGORY_ID)
REFERENCES public.CATEGORY (ID);

ALTER TABLE public.TRANSACTION
ADD CONSTRAINT USER_TRANSACTION_FK FOREIGN KEY (USER_ID)
REFERENCES public.USER (ID);

ALTER TABLE public.TRANSACTION_DETAIL
ADD CONSTRAINT TRANSACTION_TRANSACTION_DETAIL_FK FOREIGN KEY (TRANSACTION_ID)
REFERENCES public.TRANSACTION (ID);


CREATE SEQUENCE public.user_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE public.category_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE public.transaction_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE public.transaction_detail_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;